travis:
  secure:
    BINSTAR_TOKEN: t8rCvLAS9WK8Wr0Gw9V/35y6m2F91sMjf3LDvVC0XJgr4XsszNpYwCw7iKY6TMz28UO31qVAQnD2+pHInQRb3cFsmfM/o2vEC2wR7oGQoyGhdJVc2Saky9irx6341cnuBFmp/L1pCujuIY2FFhIZX8UEW/stiTucDEW9wAlGpvz+4SDPRntIq0odZ7TzfWW13pXJIGeK+3k6zTFLhWkDW1/ai/aHu1HXb5JV8bVmZ9ejXfRBqdzFBe8vDeYhGOSAjGmr5kSygltEQPEl1zIJQDOkMtHI39FYWPw0/ICuW87IlyyZWH+NYJmEtqZir0ZrV3bvQvXj+LjuU2aiVt3ImAN7IriRA1oDCMxq+6IjPNJeHmo8m20D/mPd/BaKKL/yDzknXdOD4nhHMygOFqJRnhwaEESF7zOXXiZzmkyQeIz+a8PYeg4Cw4ZK7jn30pxjLkrWsVA+3ORm/Gxq+yy2VIWFLNJAc8TBy5tVA+fD+6nxv0NgH7CY8aMVncWhGla28dhOyt8vsFXk0Juh+UqSmL+HVRLl1AP3GAeDTuH09caU/vAbxKbg23Lm2tm7cm6+OM9UPx9cEugqs+WqEBUvhgStS5ZajfUB6s7GCXptFGYt7aNijrgbvZGQvHwE2Uot0wWIk2AEC9owkVU/LRxl1SB0BAY3AuCD2J1BUqMmjdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
